name: Deploy dev og prod
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      dev-cluster:
        required: false
        default: dev-gcp
        type: string
      prod-cluster:
        required: false
        default: prod-gcp
        type: string
      dev-nais-template:
        required: false
        default: .nais/naiserator-dev.yaml
        type: string
      prod-nais-template:
        required: false
        default: .nais/naiserator-prod.yaml
        type: string

jobs:
  deploy-til-dev:
    if: github.ref_name == 'master'
    name: Deploy til dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        name: Deploy til dev
        env:
          CLUSTER: ${{ inputs.dev-cluster }}
          IMAGE: ${{ inputs.image }}
          RESOURCE: ${{ inputs.dev-nais-template }}

  deploy-til-prod:
    if: github.ref_name == 'master'
    name: Deploy til prod
    needs: deploy-til-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        name: Deploy til prod
        env:
          CLUSTER: ${{ inputs.prod-cluster }}
          IMAGE: ${{ inputs.image }}
          RESOURCE: ${{ inputs.prod-nais-template }}