name: Deploy to dev

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      dev-cluster:
        required: false
        default: dev-gcp
        type: string
      dev-nais-template:
        required: false
        default: .nais/naiserator-dev.yaml
        type: string
      git-commit:
        description: "Complete git commit to deploy"
        required: true
        default: ""


jobs:
  deploy-dev:
    name: Deploy to NAIS Dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - uses: nais/login@v0
        id: login
        with:
          team: teamsykefravr
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.dev-cluster }}
          RESOURCE: ${{ inputs.dev-nais-template }}
          VAR: image=${{ steps.login.outputs.registry }}/${{ inputs.app }}:${{ inputs.git-commit }}