name: Node build and deploy
on:
  workflow_call:
    inputs:
      dev-cluster:
        required: false
        default: dev-gcp
        type: string
      prod-cluster:
        required: false
        default: prod-gcp
        type: string
      node-version:
        required: false
        default: 14
        type: string
      distroless:
        required: false
        default: false
        type: boolean

jobs:
  build-and-publish:
    name: Bygg, test og publiser docker image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    env:
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
      - name: Install deps
        run: |
          npm install --legacy-peer-deps
      - name: Prettier check 💅
        run: |
          npx prettier --check .
      - name: Run lint and typecheck
        run: |
          npm run lint-and-typecheck
      - name: Run unit tests
        run: |
          npm run test
      - name: Build
        run: |
          npm run build
      - name: Prune
        run: |
          npm prune --omit=dev --legacy-peer-deps
      - name: Install cosign
        if:  ${{ inputs.distroless }}
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.2.3'
      - name: Verify distroless base image
        if:  ${{ inputs.distroless }}
        run: |
          cosign verify gcr.io/distroless/nodejs22-debian12 --certificate-oidc-issuer https://accounts.google.com --certificate-identity keyless@distroless.iam.gserviceaccount.com
      - name: Build and publish Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        if: (!startsWith(github.ref_name, 'dependabot'))
        with:
          team: teamsykefravr
          tag: ${{ github.sha }}

  nais-deploy:
    needs: build-and-publish
    uses: navikt/isworkflows/.github/workflows/deploy-dev-og-prod.yml@master
    with:
      image: ${{ needs.build-and-publish.outputs.image }}
      dev-cluster: ${{ inputs.dev-cluster }}
      prod-cluster: ${{ inputs.prod-cluster }}
    secrets: inherit
