name: Node build and publish image

on:
  workflow_call:
    inputs:
      git-ref:
        required: false
        type: string
      node-version:
        required: false
        default: '22'
        type: string
      publish-image:
        required: false
        default: true
        type: boolean
    outputs:
      image:
        value: ${{ jobs.build-and-publish.outputs.image }}

jobs:
  build-and-publish:
    name: Bygg, test og publiser docker image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "read"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.git-ref || github.sha }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          run_install: false
      - name: Use Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'pnpm'
      - name: Install deps
        run: |
          pnpm install --frozen-lockfile
        env:
          pnpm_config__auth: |
            {
              "https://npm.pkg.github.com/": {
                "@nais": { "authToken": "${{ secrets.GITHUB_TOKEN }}" },
                "@navikt": { "authToken": "${{ secrets.GITHUB_TOKEN }}" }
              }
            }
      - name: Format check 💅
        run: |
          pnpm run fmt:check
      - name: Run lint and typecheck 🤓
        run: |
          pnpm run lint-and-typecheck
      - name: Run unit tests
        run: |
          pnpm run test
      - name: Build
        run: |
          pnpm run build
      - name: Prune
        run: |
          pnpm prune --prod
      - name: Build and publish Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        if: inputs.publish-image
        with:
          team: teamsykefravr
          tag: ${{ inputs.git-ref || github.sha }}
