name: Node build and deploy
on:
  workflow_call:
    inputs:
      dev-cluster:
        required: false
        default: dev-gcp
        type: string
      prod-cluster:
        required: false
        default: prod-gcp
        type: string
      node-version:
        required: false
        default: 22
        type: string

jobs:
  build-and-publish:
    uses: ./.github/workflows/node-build-image-pnpm.yml
    with:
      node-version: ${{ inputs.node-version }}
      publish-image: ${{ !startsWith(github.ref_name, 'dependabot') }}
    secrets: inherit
    permissions:
      contents: "read"
      id-token: "write"
      packages: "read"

  nais-deploy:
    needs: build-and-publish
    uses: navikt/isworkflows/.github/workflows/deploy-dev-og-prod.yml@master
    with:
      image: ${{ needs.build-and-publish.outputs.image }}
      dev-cluster: ${{ inputs.dev-cluster }}
      prod-cluster: ${{ inputs.prod-cluster }}
    secrets: inherit
